### ISSUE TITLE
git clone报错了。

### ISSUE THREAD

**Issue by architectMymine** [sam9831/pick#1]
git clone.. |Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)  
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by sam9831** [comment]
你好，请提供：

- 操作系统版本
- node版本
- git版本

**Comment by sam9831** [comment]
可以尝试设置 git 的环境变量，参考这篇文章：https://blog.csdn.net/zhu1500527791/article/details/53616596
